version: '3'

services:
  odoo:
    build:
      context: .
      dockerfile: ./odoo/resources/Dockerfile
    container_name: odoo_${PROJECT}
    image: ${PROJECT}:${ODOO_VERSION}
    user: odoo
    restart: always
    ports:
      - "${PORT}:8069"
    depends_on:
      - postgres
    volumes:
      - ./odoo/config/:/etc/odoo
      - ./odoo/addons/:/mnt/extra-addons
      - ./data/odoo-data/:/var/lib/odoo
    environment:
      - HOST=postgres
      - USER=${DB_USER:-odoo}
      - PASSWORD=${DB_PASSWORD}

  postgres:
    container_name: postgres_${PROJECT}
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_POSTGRES:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER:-odoo}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
volumes:
  postgres: {}
